-- Migration from SQLite to Supabase Postgres
-- Run this in your Supabase SQL Editor to prepare your remote database for Edge Functions

-- 1. Users table (Custom Table so frontend Auth still works exactly the same)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Checkins
CREATE TABLE IF NOT EXISTS public.checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id),
  date TEXT NOT NULL,
  water_intake INTEGER DEFAULT 0,
  medicine_taken BOOLEAN DEFAULT FALSE,
  sleep_hours FLOAT DEFAULT 0,
  symptoms TEXT,
  mood TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

-- 3. AI Suggestions
CREATE TABLE IF NOT EXISTS public.suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id),
  suggestion TEXT NOT NULL,
  type TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Reminders
CREATE TABLE IF NOT EXISTS public.reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id),
  time TEXT NOT NULL,
  text TEXT NOT NULL,
  type TEXT DEFAULT 'medicine',
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Voice Logs
CREATE TABLE IF NOT EXISTS public.voice_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id),
  reminder_id BIGINT REFERENCES public.reminders(id),
  response TEXT,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Recovery Plans
CREATE TABLE IF NOT EXISTS public.recovery_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT UNIQUE NOT NULL REFERENCES public.users(id),
  plan_json TEXT NOT NULL,
  food_preference TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Patient Symptoms Summary
CREATE TABLE IF NOT EXISTS public.patient_symptoms_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL UNIQUE,
  summary TEXT NOT NULL,
  feels_better BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure RLS is disabled temporarily for hackathon edge-function migration
-- Or setup basic RLS allowing all if necessary:
-- ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
