-- ============================================================
-- Supabase Migration: Swasthya Bandhu App Tables
-- Run this in Supabase Dashboard → SQL Editor
-- ============================================================

-- 1. Users table (custom, app-managed auth)
CREATE TABLE IF NOT EXISTS public.users (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username  TEXT UNIQUE NOT NULL,
  email     TEXT UNIQUE NOT NULL,
  password  TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Daily check-ins
CREATE TABLE IF NOT EXISTS public.checkins (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  date           TEXT NOT NULL,
  water_intake   INTEGER DEFAULT 0,
  medicine_taken BOOLEAN DEFAULT FALSE,
  sleep_hours    FLOAT DEFAULT 0,
  symptoms       TEXT,
  mood           TEXT,
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date)
);

-- 3. AI suggestions
CREATE TABLE IF NOT EXISTS public.suggestions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  suggestion TEXT NOT NULL,
  type       TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Reminders
CREATE TABLE IF NOT EXISTS public.reminders (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  time         TEXT NOT NULL,
  text         TEXT NOT NULL,
  type         TEXT DEFAULT 'medicine',
  completed    BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Voice Logs
CREATE TABLE IF NOT EXISTS public.voice_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  reminder_id BIGINT REFERENCES public.reminders(id) ON DELETE SET NULL,
  response    TEXT,
  message     TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Recovery Plans
CREATE TABLE IF NOT EXISTS public.recovery_plans (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT UNIQUE NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  plan_json       TEXT NOT NULL,
  food_preference TEXT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Patient Symptoms Summary
CREATE TABLE IF NOT EXISTS public.patient_symptoms_summary (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id  BIGINT NOT NULL UNIQUE,
  summary     TEXT NOT NULL,
  feels_better BOOLEAN DEFAULT FALSE,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security for all tables 
-- (Edge Function uses service-role key which bypasses RLS anyway)
ALTER TABLE public.users                  DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkins               DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.suggestions            DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminders              DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_logs             DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.recovery_plans         DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_symptoms_summary DISABLE ROW LEVEL SECURITY;
